### ISSUE TITLE
Pascal Binding Deconstructor does not work when named other than "ReleaseInstance".

### ISSUE THREAD

**Issue by alexanderoster** [Autodesk/AutomaticComponentToolkit#20]

**Comment by alexanderoster** [comment]
Need to change
	w.Writeln ("    FWrapper.ReleaseInstance(self);");
with
	w.Writeln ("    FWrapper.%s(self);", componentdefinition.Global.ReleaseMethod);

as it is done in the Cpp bindings.

**Comment by martinweismann** [comment]
Thanks for the fix!
