### ISSUE TITLE
C++ implementation issue with gcc

### ISSUE THREAD

**Issue by dabastynator** [Autodesk/AutomaticComponentToolkit#26]
On gcc the c++ implementation fails to compile because of the order of classes xxx_interfaces.hpp
error: invalid use of incomplete type ‘class xxx::Impl::IxxxBaseClass’
note: forward declaration of ‘class xxx::Impl::IxxxBaseClass’

**Comment by dabastynator** [comment]
Turned out that defining the baseclass in top of the act.xml solved the issue.
Maybe it's a nice-to-have to first write the baseclass followed by other classes in the _interfaces.hpp?

**Comment by martinweismann** [comment]
Did you use the current develop-branch?
Commit https://github.com/Autodesk/AutomaticComponentToolkit/commit/747dcd6ad46927bb88b846289b45f72649d14f14 should have fixed the treatment of the base-class. Starting from 1.5, one MUST define a baseclass-attribute in the global-element that refers to a class-element in the XML file.

**Comment by dabastynator** [comment]
Yes, that happened on the develop-branch.
My xml has a base-class-reference in the global-element. But i put the base-class-element below all other classes and it seems like the order of classes in the xml is the same order as the c++ classes in the _interfaces.hpp
Normally that should be no deal, because in the top of _interfaces.hpp all classes are listed, followed by the declaration. But it seems like this is not enough for gcc.
Anyhow, putting the base-class-element to the top of my act.xml solved the gcc problem, so we can close this issue.
