### ISSUE TITLE
C++ generated from structarray contradicts with its comment and doesn't have array length

### ISSUE THREAD

**Issue by szliu-a** [Autodesk/AutomaticComponentToolkit#56]
Here's part of my IDL:
```xml
<functiontype name="ShowItems">
	<param name="Items" type="structarray" class="MenuItem" pass="in"/>
</functiontype>
```
And it generates c++ code:
```c++
  /**
  * ShowItems - 
  *
  * @param[in] nItemsBufferSize - Number of elements in buffer
  * @param[in] pItemsBuffer - MenuItem buffer of 
  */
  typedef void(*ShowItems)(MyAPI::sMenuItem *);
```
Here only a pointer (pItemsBuffer) is generated as parameter, but not the size of the array.
I.e. nItemsBufferSize is missing.

I am using ACT version 1.5 on Windows.

**Comment by martinweismann** [comment]
@szliu-a : thanks for bringing this up.

We'll include a fix (https://github.com/Autodesk/AutomaticComponentToolkit/pull/57) to this problem in release 1.6.0.
