### ISSUE TITLE
lib3mf requires AutomaticComponentToolkit not available for raspbian/ARM

### ISSUE THREAD

**Issue by cwuebker2** [Autodesk/AutomaticComponentToolkit#75]
In trying to build OpenSCAD for Raspbian Buster, I see that
  https://github.com/koendv/openscad-raspberrypi
has a procedure for building lib3mf.  When I tried to use that
procedure, it failed, apparently because lib3mf requires
the AutomaticComponentToolkit and act.linux assumes an
x86-based Linux.
I read about building the AutomaticComponentToolkit on raspbian;
apparently the process starts with having an already-built act.something.

If the only thing missing is an ARM-based act.raspbian, could you provide it
in this repository?

If not, any detailed advice on how to build an act.raspbian on Raspbian Buster
would be appreciated.

**Comment by martinweismann** [comment]
Hi @cwuebker2 ,

yes, we are missing an arm executable of ACT. Can you try building the content of this PR https://github.com/Autodesk/AutomaticComponentToolkit/pull/76 (by running Build/build.sh or Build/build.bat)?

Or you can test this binary here:
[act.arm.zip](https://github.com/Autodesk/AutomaticComponentToolkit/files/3832759/act.arm.zip)

**Comment by cwuebker2** [comment]
I did a git clone of PR #76, added the latest stable **golang** to the Raspbian Buster OS and -- using your instructions -- quickly built the 3 files, act.darwin, act.exe & act.linux.  I then copied the 3 files under lib3mf/AutomaticComponentToolkit/bin and build lib3mf.  Thanks for the fast & working fix.  I hope that act.arm will be part of the main ACT branch in the future.

  After the build, I copy/edited lib3mf/lib3MF.pc.in to /usr/share/pkgconfig/lib3MF.pc so OpenSCAD's qmake-qt4 could find the /usr/local/lib/lib3mf.so library.  After that file was in place, OpenSCAD built several modules before its Preferences.cc compile failed -- it couldn't convert a **const QString** to a **const &string**, and I'm pretty sure that problem isn't related to your fix.

  Thanks for the quick & excellent fix -- I'm ready to close this with the comment "User happy!" but am new to reporting problems here & not sure whether I should close this or you should.

Carl

**Comment by martinweismann** [comment]
Great! I am happy that this works for you.

After the next release of ACT, I'll add the new act.arm-binary to the lib3mf-repo.
If you find/need more binaries for OpenSCAD to build on other platforms, let me know by creating another issue here!
