### ISSUE TITLE
[go] Avoid CGO in auto generated code

### ISSUE THREAD

**Issue by qmuntal** [Autodesk/AutomaticComponentToolkit#91]
The auto generate Go implementation has a hard-coded import to `C` package in order to include `string.h`.

I don't see any call to `C` nor any use of the included header, so I think it can be removed. Removing this import will greatly simplify cross-compilation, as it is the only reason auto generated packages must be compiled using CGO_ENABLED=1, thus disabling the built-in go cross-compilation capabilities.

I've tested this change in lib3mf and it is working, but it could be that I'm missing something.

**Comment by alexanderoster** [comment]
Hi qmuntal,

thank you, we will fix this! I would love to get some more input for the go headers, especially how to do them for Linux.

Best,

Alex

**Comment by qmuntal** [comment]
The string.h header is not necessary and this seems to be the only reason to import C package, so both can be removed. With this you won't have to worry about any header in any platform ;)

**Comment by qmuntal** [comment]
@alexanderoster now I get you question about the Linux headers. It is not possible to load a shared library using syscal.LoadLibrary in Linux, they have to be linked using cgo.

I didn't recall one Linux when creating this post. If we want to have the same code for any platform we will need to use cgo.
